finished hw5
sergey-sitro/hillel-js-automation pull request #5
Opened 2024-01-29 18:33 UTC by sergey-sitro

2024-01-29 21:44 UTC, sttaran requested changes

2024-01-29 21:44 UTC, sttaran commented on hw5/task1.js
> +const rectangleAreaAF = (width, height) => width * height;
function name should represent an action but not a noun

2024-01-29 21:44 UTC, sttaran commented on hw5/task2.js
> +    return age && age >= 18;
return age >= 18;

2024-01-29 21:44 UTC, sttaran commented on hw5/task2.js
> +    return age && age >= 18;
you function should return boolean

But I am wondering what did you want to achieve? It might make sense but in particular situations

2024-01-30 08:18 UTC, sergey-sitro commented on hw5/task2.js
> +    return age && age >= 18;
This is just for handling 'undefined' value of age. Looks like it is out of scope so I will leave 'return age >= 18'

2024-01-30 08:58 UTC, sttaran commented on hw5/task2.js
> +    return age && age >= 18;
if it would be undefined then function would return undefined too in previous implementation. I see your point. But we can validate value and return false or throw an error if it is undefined

2024-01-30 08:58 UTC, sttaran approved these changes

2024-01-30 08:59 UTC, merged